### PR TITLE
Fix Markdown Issue

### LINKED ISSUE #1187: The markdown table is parsed unexpectedly in css-loader documentation page
In the "Options" section of the [css-loader](https://webpack.js.org/loaders/css-loader/#options) documentation.

image

### PR DESCRIPTION
**Pull request by skipjack**
Fix issue with escaped `|` not being taken into account.

This is allowed in GFM but not supported by marked. See this issue:
https://github.com/chjj/marked/issues/595

Fixes #1187

cc @Alex1990 @NejcZdovc

### CODE REVIEW

File: utilities/markdown.js [hunk 1]
```diff
@@ -234,6 +234,23 @@ function handleTable(t) {
     let row = t.cells[i];
     cell = '';
 
+
+    // Fix escaped '|' characters
+    // See https://github.com/chjj/marked/issues/595
+    let erroneous = row.map(item => item.endsWith('\\') ? item : null).filter(item => item !== null)
```
Comment (bebraw) [inline utilities/markdown.js]: I might write this as

```javascript
let erroneous = row.map(item => item.endsWith('\\') && item).filter(item => item)
```

Same result.

Comment (NejcZdovc) [inline utilities/markdown.js]: ++
