### PR TITLE
fix(a11y): use distinct alt text for footer license icons

### LINKED ISSUE #7970: Duplicate screen reader text in footer license link
The footer license link contains two images that both use the same alt text
"Creative Commons License".

Location:
src/components/Footer/Footer.jsx:87–89

Because both images have identical alt text, screen readers may announce:

"Creative Commons License, Creative Commons License, link"

This creates unnecessary repetition and slightly reduces accessibility for
non-visual users.

Suggested improvement:

Provide distinct alt text for each icon so screen readers announce
meaningful and non-duplicated descriptions.

Example:

Creative Commons license icon
Creative Commons Attribution icon

### PR DESCRIPTION
**Pull request by mr-baraiya**
Fixes #7970

The footer license link contained two images with identical alt text
("Creative Commons License").

Screen readers may announce duplicated text.

This change provides distinct alt text for each Creative Commons icon
to avoid duplicate announcements by screen readers.

### CODE REVIEW

**Comment by mr-baraiya** [comment]
Thanks for the feedback! I’ve updated the footer icons to use distinct alt text for each image.

File: src/components/Footer/Footer.jsx [hunk 1]
```diff
@@ -85,8 +85,13 @@ const Footer = () => (
...
         <Link className="footer__link footer__license" to="/license">
-          <img alt="Creative Commons License" src={CC} width={25} height={25} />
-          <img alt="Creative Commons License" src={BY} width={25} height={25} />
+          <img alt="Creative Commons license" src={CC} width={25} height={25} />
+          <img
+            alt="Creative Commons Attribution icon"
+            src={BY}
+            width={25}
+            height={25}
+          />
```
Comment (alexander-akait) [inline src/components/Footer/Footer.jsx:99]: It should be `Creative Commons License (CC)` and  `Creative Commons Attribution (CC BY)`

Comment (mr-baraiya) [reply src/components/Footer/Footer.jsx:99]: Thanks for the suggestion! I've updated the footer icons with the requested alt text:

* **Creative Commons License (CC)**
* **Creative Commons Attribution (CC BY)**

Please let me know if anything else needs adjustment.
